In [1]:
import mlxtend
import numpy as np
import pandas as pd

In [2]:
data = np.array([
    ['우유', '기저귀', '쥬스'],
    ['양상추', '기저귀', '맥주'],
    ['우유', '양상추', '기저귀', '맥주'],
    ['양상추', '맥주']
])

In [3]:
data = np.array([
    ['우유', '기저귀', '쥬스'],
    ['양상추', '기저귀', '맥주'],
    ['우유', '양상추', '기저귀', '맥주'],
    ['양상추', '맥주']
])

## Apriori 알고리즘

In [4]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
te_ary

array([[ True, False, False,  True,  True],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True, False],
       [False,  True,  True, False, False]])

In [5]:
te.columns_ # 기록정보 저장

['기저귀', '맥주', '양상추', '우유', '쥬스']

In [6]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

     기저귀     맥주    양상추     우유     쥬스
0   True  False  False   True   True
1   True   True   True  False  False
2   True   True   True   True  False
3  False   True   True  False  False

In [7]:
%%time
from mlxtend.frequent_patterns import apriori

apriori(df, min_support=0.5, use_colnames=True)

CPU times: user 12.6 ms, sys: 119 µs, total: 12.7 ms
Wall time: 18.2 ms

   support        itemsets
0     0.75           (기저귀)
1     0.75            (맥주)
2     0.75           (양상추)
3     0.50            (우유)
4     0.50       (기저귀, 맥주)
5     0.50      (양상추, 기저귀)
6     0.50       (우유, 기저귀)
7     0.75       (양상추, 맥주)
8     0.50  (양상추, 기저귀, 맥주)

## FP-Growth 알고리즘

In [8]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

     기저귀     맥주    양상추     우유     쥬스
0   True  False  False   True   True
1   True   True   True  False  False
2   True   True   True   True  False
3  False   True   True  False  False

In [9]:
%%time
from mlxtend.frequent_patterns import fpgrowth

fpgrowth(df, min_support=0.5, use_colnames=True)

CPU times: user 4.46 ms, sys: 0 ns, total: 4.46 ms
Wall time: 5.08 ms

   support        itemsets
0     0.75           (기저귀)
1     0.50            (우유)
2     0.75           (양상추)
3     0.75            (맥주)
4     0.50       (기저귀, 맥주)
5     0.50      (양상추, 기저귀)
6     0.50  (양상추, 기저귀, 맥주)
7     0.50       (우유, 기저귀)
8     0.75       (양상추, 맥주)

In [10]:
#import pandas as pd
#from mlxtend.preprocessing import TransactionEncoder
#추가분
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth, association_rules

association=fpgrowth(df, min_support=0.1, use_colnames=True)
association_rules(association, metric='confidence', min_threshold=0.5, support_only=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(기저귀),(맥주),0.75,0.75,0.50,0.666667,0.888889,-0.0625,0.75
1,(맥주),(기저귀),0.75,0.75,0.50,0.666667,0.888889,-0.0625,0.75
2,(양상추),(기저귀),0.75,0.75,0.50,0.666667,0.888889,-0.0625,0.75
3,(기저귀),(양상추),0.75,0.75,0.50,0.666667,0.888889,-0.0625,0.75
4,"(양상추, 기저귀)",(맥주),0.50,0.75,0.50,1.000000,1.333333,0.1250,inf
5,"(양상추, 맥주)",(기저귀),0.75,0.75,0.50,0.666667,0.888889,-0.0625,0.75
6,"(기저귀, 맥주)",(양상추),0.50,0.75,0.50,1.000000,1.333333,0.1250,inf
7,(양상추),"(기저귀, 맥주)",0.75,0.50,0.50,0.666667,1.333333,0.1250,1.50
8,(기저귀),"(양상추, 맥주)",0.75,0.75,0.50,0.666667,0.888889,-0.0625,0.75
9,(맥주),"(양상추, 기저귀)",0.75,0.50,0.50,0.666667,1.333333,0.1250,1.50
10,(우유),(기저귀),0.50,0.75,0.50,1.000000,1.333333,0.1250,inf
11,(기저귀),(우유),0.75,0.50,0.50,0.666667,1.333333,0.1250,1.50
12,(우유),(맥주),0.50,0.75,0.25,0.500000,0.666667,-0.1250,0.50
13,(우유),(양상추),0.50,0.75,0.25,0.500000,0.666667,-0.1250,0.50
14,"(기저귀, 우유)",(맥주),0.50,0.75,0.25,0.500000,0.666667,-0.1250,0.50
15,"(우유, 맥주)",(기저귀),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
16,"(기저귀, 맥주)",(우유),0.50,0.50,0.25,0.500000,1.000000,0.0000,1.00
17,(우유),"(기저귀, 맥주)",0.50,0.50,0.25,0.500000,1.000000,0.0000,1.00
18,"(양상추, 우유)",(기저귀),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
19,"(기저귀, 우유)",(양상추),0.50,0.75,0.25,0.500000,0.666667,-0.1250,0.50
20,"(양상추, 기저귀)",(우유),0.50,0.50,0.25,0.500000,1.000000,0.0000,1.00
21,(우유),"(양상추, 기저귀)",0.50,0.50,0.25,0.500000,1.000000,0.0000,1.00
22,"(양상추, 우유)",(맥주),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
23,"(우유, 맥주)",(양상추),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
24,(우유),"(양상추, 맥주)",0.50,0.75,0.25,0.500000,0.666667,-0.1250,0.50
25,"(양상추, 기저귀, 우유)",(맥주),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
26,"(양상추, 우유, 맥주)",(기저귀),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
27,"(기저귀, 우유, 맥주)",(양상추),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
28,"(양상추, 기저귀, 맥주)",(우유),0.50,0.50,0.25,0.500000,1.000000,0.0000,1.00
29,"(양상추, 우유)","(기저귀, 맥주)",0.25,0.50,0.25,1.000000,2.000000,0.1250,inf
30,"(기저귀, 우유)","(양상추, 맥주)",0.50,0.75,0.25,0.500000,0.666667,-0.1250,0.50
31,"(우유, 맥주)","(양상추, 기저귀)",0.25,0.50,0.25,1.000000,2.000000,0.1250,inf
32,"(양상추, 기저귀)","(우유, 맥주)",0.50,0.25,0.25,0.500000,2.000000,0.1250,1.50
33,"(기저귀, 맥주)","(양상추, 우유)",0.50,0.25,0.25,0.500000,2.000000,0.1250,1.50
34,(우유),"(양상추, 기저귀, 맥주)",0.50,0.50,0.25,0.500000,1.000000,0.0000,1.00
35,(쥬스),(우유),0.25,0.50,0.25,1.000000,2.000000,0.1250,inf
36,(우유),(쥬스),0.50,0.25,0.25,0.500000,2.000000,0.1250,1.50
37,(쥬스),(기저귀),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
38,"(쥬스, 우유)",(기저귀),0.25,0.75,0.25,1.000000,1.333333,0.0625,inf
39,"(기저귀, 우유)",(쥬스),0.50,0.25,0.25,0.500000,2.000000,0.1250,1.50
40,"(쥬스, 기저귀)",(우유),0.25,0.50,0.25,1.000000,2.000000,0.1250,inf
41,(우유),"(쥬스, 기저귀)",0.50,0.25,0.25,0.500000,2.000000,0.1250,1.50
42,(쥬스),"(기저귀, 우유)",0.25,0.50,0.25,1.000000,2.000000,0.1250,inf
43,(양상추),(맥주),0.75,0.75,0.75,1.000000,1.333333,0.1875,inf
44,(맥주),(양상추),0.75,0.75,0.75,1.000000,1.333333,0.1875,inf